config/routes.rb
Rails.application.routes.draw do
  resources :containers 
  resources :items
  

  root 'containers#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/container.rb
class Container < ApplicationRecord
    has_many :items, dependent: :destroy
    accepts_nested_attributes_for :items, allow_destroy: true

    FR20 = "FR20"
    FR40 = "FR40"
    OT20 = "OT20"
    OT40 = "OT40"

    CONTAINER_RESULT_NG = "NG"
    CONTAINER_RESULT_OK = "OK"
    CONTAINER_RESULT_TBA = "TBA"
    
    validates :container_type, presence: true;
end

app/controllers/containers_controller.rb
class ContainersController < ApplicationController
  include ContainersHelper
  before_action :set_container, only: %i[ show edit update destroy ]
  
  # GET /containers or /containers.json
  def index
    @containers = Container.all
  end

  # GET /containers/1 or /containers/1.json
  def show
    handle_input()
    @container
    @result
    
  end

  # GET /containers/new
  def new
    @container = Container.new
    @item = @container.items.build
    
  end

  # GET /containers/1/edit
  def edit
  end

  # POST /containers or /containers.json
  def create
    render js: container_params
    @container = Container.new(container_params)

  
    respond_to do |format|
      if @container.save
        format.html { render container_url(@container), notice: "Container was successfully created." }
        format.json { render :show, status: :created, location: @container }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.js
        format.json { render json: @container.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /containers/1 or /containers/1.json
  def update
    respond_to do |format|
      if @container.update(container_params)
        format.html { redirect_to container_url(@container), notice: "Container was successfully updated." }
        format.js
        format.json { render :show, status: :ok, location: @container }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.js
        format.json { render json: @container.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /containers/1 or /containers/1.json
  def destroy
    @container.destroy

    respond_to do |format|
      format.html { redirect_to containers_url, notice: "Container was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_container
      @container = Container.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def container_params
      params.require(:container).permit(:container_type, items_attributes: [:packing_style,:length,:width,:height,:weight,:cog_height_type,:cog_height])
    end

    def handle_input
      @result = convert_input_to_result()
      container_type = @container.container_type
      if(container_type == Container::FR20 || container_type == Container::FR40)
        handle_flat_track_item(@container,@result)
      else
        handle_open_top_item(@container,@result)
      end
    end

    def convert_input_to_result
        result = {}
        result['container_type'] = @container.container_type
        items = Array.new(@container.items.count)
        items.each_with_index do |item,index_of_item|
          items[index_of_item] = Hash.new
        end
        result['items'] = items
        @container.items.each_with_index do |item,index_of_item|
          result['items'][index_of_item]['packing_style'] = item.packing_style
          result['items'][index_of_item]['length'] = item.length
          result['items'][index_of_item]['width'] = item.width
          result['items'][index_of_item]['height'] = item.height
          result['items'][index_of_item]['weight'] = item.weight
          result['items'][index_of_item]['cog_height_type'] = item.cog_height_type
          result['items'][index_of_item]['cog_height'] = item.cog_height
        end
        return result
    end
end

app/helpers/containers_helper.rb
module ContainersHelper
    MESSAGE1 = "Further evaluation is required. Reason : Packing style"
    MESSAGE2 = "Width exceeds criteria"
    MESSAGE3 = "Length exceeds criteria. Further evaluation by SCM is required"
    MESSAGE4 = "Weight Distribution exceeds criteria. Further evaluation by SCM is required."
    MESSAGE5 = "Height exceeds criteria"
    MESSAGE6 = "COG Height exceeds criteria"
    MESSAGE7 = "Weight concentration exceeds criteria"
    MESSAGE8 = "Length may exceeds container dimension"
    MESSAGE9 = "Weight may exceeds max payload"
    MESSAGE10 = "This acceptance check has to be done again after COG height is determined. This result assuming that the COG is half height of the cargo as you inputted 'TBA' for COG." 


    def handle_flat_track_item(container, result)
        container.items.each_with_index do |item,index_of_item|
            packing_style_item = item.packing_style
            if(packing_style_item.upcase == Item::PACKING_STYLE_BARE || packing_style_item.upcase == Item::PACKING_STYLE_SKID)
                update_result_item_ng(result,index_of_item)
                update_message_item(result,ContainersHelper::MESSAGE1,index_of_item)
            end
            check_max_width(item,container,index_of_item,result)
        end
    end

    def check_max_width(item,container,index_of_item, result)
        if(item.width > Item::WIDTH_20FR_MAX || item.width > Item::WIDTH_40FR_MAX)
            update_result_item_ng(result,index_of_item)
            update_message_item(result,ContainersHelper::MESSAGE2,index_of_item)
        end
        check_length(item,container,result,index_of_item)
    end
    
    def check_length(item,container,result,index_of_item)
        if(item.length > Item::LENGTH_20FR_MAX || item.length > Item::LENGTH_40FR_MAX)
            update_result_item_ng(result,index_of_item)
            update_message_item(result,ContainersHelper::MESSAGE3,index_of_item)
        end
        flat_track_check_weight_distribution(item,container,result,index_of_item)
    end

    def flat_track_check_weight_distribution(item,container,result,index_of_item)
        length_item = item.length
        weight_item = item.weight
        container_type = container.container_type
        if(container_type == Container::FR20)
            flat_track_check_weight_distribution_FR20(item,container_type,result,index_of_item)
        else
            flat_track_check_weight_distribution_FR40(item,container_type,result,index_of_item)
        end
        check_height(item,container,result,index_of_item)
    end

    def flat_track_check_weight_distribution_FR20(item,container_type,result,index_of_item)
        length_item = item.length
        weight_item = item.weight
        start_range = range_length(length_item,container_type)[0]
        end_range = range_length(length_item,container_type)[1]
        if( (weight_item > convert_to_ton(Item::WEIGHT_20FR_MAX[end_range])   )   || 
            (weight_item < convert_to_ton(Item::WEIGHT_20FR_MAX[start_range]) )
        )
            update_result_item_ng(result,index_of_item)
            update_message_item(result,ContainersHelper::MESSAGE4,index_of_item)
        end
    end

    def flat_track_check_weight_distribution_FR40(item,container_type,result,index_of_item)
        length_item = item.length
        weight_item = item.weight
        start_range = range_length(length_item,container_type)[0]
        end_range = range_length(length_item,container_type)[1]
        if( (weight_item > convert_to_ton(Item::WEIGHT_40FR_MAX[end_range]) ) ||
            (weight_item < convert_to_ton(Item::WEIGHT_40FR_MAX[start_range]) )
        )
            update_result_item_ng(result,index_of_item)
            update_message_item(result,ContainersHelper::MESSAGE4,index_of_item)
        end
    end    

    def check_height(item,container,result,index_of_item)
        height_item = item.height
        if(height_item > Item::MAX_HEIGHT || height_item < Item::MIN_HEIGHT)
            update_result_item_ng(result,index_of_item)
            update_message_item(result,ContainersHelper::MESSAGE5,index_of_item)
        end
        flat_track_cog_calculation(item,container,result,index_of_item)
        
    end

    def flat_track_cog_calculation(item,container,result,index_of_item)
        cog_height_type = item.cog_height_type.downcase
        case cog_height_type
        when Item::COG_HEIGHT_TYPE_HALF_OF_CARGO_HEIGHT_OR_LESS
            over_width_check(item,container,result,index_of_item)
        when Item::COG_HEIGHT_TYPE_MANUAL
            over_width_check(item,container,result,index_of_item)
        when Item::COG_HEIGHT_TYPE_TBA
            update_message_container(result,ContainersHelper::MESSAGE10,container)
            over_width_check(item,container,result,index_of_item)
        end
    end    

    def over_width_check(item,container,result,index_of_item)
        width_item = item.width
        container_type = container.container_type
        if(container_type == Container::FR20)
            over_width_check_FR20(item,container,result,index_of_item)
        else
            over_width_check_FR40(item,container,result,index_of_item)
        end
    end

    def over_width_check_FR20(item,container,result,index_of_item)
        width_item = item.width
        if(width_item <= Item::WIDTH_20FR)
            cog_height_check_2(item,container,result,index_of_item)
        else
            cog_height_check_1(item,container,result,index_of_item)
        end 
    end

    def over_width_check_FR40(item,container,result,index_of_item)
        width_item = item.width
        if(width_item <= Item::WIDTH_40FR)
            cog_height_check_2(item,container,result,index_of_item)
        else
            cog_height_check_1(item,container,result,index_of_item)
        end 
        
    end

    def cog_height_check_2(item,container,result,index_of_item)
        width_item = item.width
        total_height = get_total_height_of_item_in_container(container)
        cog_value = (total_height/2).to_f
        
        if(cog_value > width_item * 0.865)
            update_result_item_ng(result,index_of_item)
            update_message_item(result,ContainersHelper::MESSAGE6,index_of_item)
        end
        update_result_item_ok(result,index_of_item)
        total_length_check(item,container,result,index_of_item)
    end
    
    def cog_height_check_1(item,container,result,index_of_item)
        width_item = item.width
        total_height = get_total_height_of_item_in_container(container)
        cog_value = (total_height/2).to_f
        
        if(cog_value > Item::COG_HEIGHT_FLAT_TRACK)
            update_result_item_ng(result,index_of_item)
            update_message_item(result,ContainersHelper::MESSAGE6,index_of_item)
        end
        update_result_item_ok(result,index_of_item)
        total_length_check(item,container,result,index_of_item)
    end

    def get_total_height_of_item_in_container(container)
        total_height = 0
        container.items.each do |item|
            if(item.cog_height_type.downcase == Item::COG_HEIGHT_TYPE_MANUAL)
                height_item = item.height
            else
                height_item = item.height*0.5
            end
            if(total_height < height_item)
                total_height = height_item
            end
        end
        return total_height
    end

    def range_length(number,container_type)
        if(container_type == Container::FR20)
            divide = (number/50).to_i
            start_range = 50 * divide
            end_range = 50 * (divide + 1)
        else
            divide = (number/100).to_i
            start_range = 100 * divide
            end_range = 100 * (divide + 1)
        end
        
        return [start_range,end_range]
    end

    def handle_open_top_item(container,result)
        container.items.each_with_index do |item,index_of_item|
            packing_style_item = item.packing_style
            if(packing_style_item.upcase == Item::PACKING_STYLE_BARE)
                update_result_item_ng(result,index_of_item)
                update_message_item(result,ContainersHelper::MESSAGE1,index_of_item)
            end
            open_top_cog_height_calculation(item,container,result,index_of_item)
        end
    end

    def open_top_cog_height_calculation(item,container,result,index_of_item)
        cog_height_type = item.cog_height_type.downcase
        case cog_height_type
        when Item::COG_HEIGHT_TYPE_TBA
            update_message_container(result,ContainersHelper::MESSAGE10,container)
            
            open_top_cog_value_check(item,container,result,index_of_item)
        when Item::COG_HEIGHT_TYPE_MANUAL
            open_top_cog_value_check(item,container,result,index_of_item)
            
        when Item::COG_HEIGHT_TYPE_HALF_OF_CARGO_HEIGHT_OR_LESS
            open_top_cog_value_check(item,container,result,index_of_item)
           
        end
    end

    def open_top_cog_value_check(item,container,result,index_of_item)
        cog_height_type = item.cog_height_type.downcase
        if( (cog_height_type == Item::COG_HEIGHT_TYPE_HALF_OF_CARGO_HEIGHT_OR_LESS) ||
            (cog_height_type == Item::COG_HEIGHT_TYPE_TBA)
        )
            cog_value = item.height*0.5
        else
            cog_value = item.height
        end
        
        if(cog_value > Item::COG_HEIGHT_OPEN_TOP)
            update_result_item_ng(result,index_of_item)
            update_message_item(result, ContainersHelper::MESSAGE6,index_of_item)
        end
        open_top_weight_distribution_check(item,container,result,index_of_item)
    end

    def open_top_weight_distribution_check(item,container,result,index_of_item)
        weight_item = item.weight
        length_item = item.length.to_f
        length_item = convert_to_meter(length_item)
        max_weight_distribution = (weight_item / length_item).to_f
        
        container_type = container.container_type

app/views/containers/_form.html.erb
<%= form_with(model: container, id: "form_container", local: false) do |form|  %>
 

  <div class="container_group">
    <%= form.label :container_type %>
    <%= form.select :container_type, ['FR20', 'FR40', 'OT20','OT40']%>
  </div>

  <table class="item_group">
    <tr class="title_item">
        <th rowspan="2" class="title_item" >SEQ</th>
        <th rowspan="2" class="title_item">PACKING STYLE</th>
        <th colspan="4" class="title_item"> SIZE </th>
        <th colspan="2" class="title_item"> GROSS WEIGHT </th>
        <th colspan="2" class="title_item"> CENTER OF GRAVITY HEIGHT</th>
        <th rowspan="2"  colspan="2" class="title_item"> ACTIONS </th>
    </tr>
    
      <tr class="sub_title_item">
        <td>LENGTH</td>
        <td>WIDTH</td>
        <td>HEIGHT</td>
        <td>UNIT</td>
        <td>WEIGHT</td>
        <td>UNIT</td>
        <td>HEIGHT</td>
        <td>UNIT</td>
      </tr>
      <% if @container.items.exists? %>
        <% @container.items.each_with_index do |item,index_of_item| %>
          <tr class="item_result">
            <td><%= index_of_item + 1 %></td>
            <td><%= item.packing_style %></td>
            <td><%= item.length %></td>
            <td><%= item.width %></td>
            <td><%= item.height %></td>
            <td>cm</td>
            <td><%= item.weight %></td>
            <td>ton </td>
            <td><%= item.cog_height %></td>
            <td>cm</td>
            <td><%= link_to edit_item_path(item), class: "edit-item" do %>
                <i class="fas fa-edit "></i>
                <%end%>
            </td>
            <td><%= link_to  item, method: :delete, data: { confirm: 'Are you sure?' } do %>
                <i class="fas fa-trash-alt"></i>
                <%end%>
            </td>
          </tr>
        <% end%>
      <% end%>

      
  </table>

  <div class="actions d-flex flex-row-reverse btn-group-action">
    <div class="btn btn-success" id="add-btn">
      Add
    </div>
    <%= form.submit class: "btn btn-primary item_submit" %>
    
  </div>
<% end %>

app/views/containers/edit.html.erb
<h1 class="title m-3 p-4">Editing Container</h1>

<%= render 'form', container: @container %>

app/views/containers/index.html.erb
<div class="container_group">

<h1>Containers</h1>

<table class="mt-3">
  <thead>
    <tr class="container_title">
      <th>Container type</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @containers.each do |container| %>
      <tr class="container_result">
        <td><%= container.container_type  %></td>
        <td>
          <%= link_to container do %>
            <i class="fas fa-eye"></i>
          <%end%>
        </td>
        <td>
          <%= link_to edit_container_path(container) do %>
            <i class="fas fa-edit"></i>
          <%end%>
        </td>
        <td>
          <%= link_to container, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <i class="fas fa-trash-alt"></i>
          <%end%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

  <div class="btn btn-success float-end mt-5">
    <%= link_to 'New Container', new_container_path %>
  </div>

</div>

app/views/containers/new.html.erb
<div class="new-container">
    <h1 class="title m-3 p-4">New Container</h1>

    <%= render 'form', container: @container %>
    <div id="float-form-item ">
        <div class="float_form_area">
        <%= render 'items/form', item: @item %>
        </div>
    </div>
</div>

app/views/containers/show.html.erb
<div id="form_container">
  <% @result %>
<p>
  <strong>Container type:</strong>
  <%= @result['container_type'] %>
</p>
 

  <table class="item_group">
    <tr class="title_item">
        <th rowspan="2" class="title_item" >SEQ</th>
        <th rowspan="2" class="title_item">PACKING STYLE</th>
        <th colspan="4" class="title_item"> SIZE </th>
        <th colspan="2" class="title_item"> GROSS WEIGHT </th>
        <th class="title_item"> COG HEIGHT</th>
        <th   class="title_item">RESULT </th>
        <th colspan="2" rowspan="2" class="title_item"> REMARKS</th>
    </tr>
    
    <tr class="sub_title_item">
      <td>LENGTH</td>
      <td>WIDTH</td>
      <td>HEIGHT</td>
      <td>UNIT</td>
      <td>WEIGHT</td>
      <td>UNIT</td>
      <td>HEIGHT</td>
      <td>ACCEPTANCE</td>
    </tr>
   
    <% @result['items'].each_with_index do |item,index_of_item| %>
      <tr class="item_result">
        <td><%= index_of_item + 1 %></td>
        <td><%= item["packing_style"] %></td>
        <td><%= item['length'] %></td>
        <td><%= item['width'] %></td>
        <td><%= item['height'] %></td>
        <td>cm</td>
        <td><%= item['weight'] %></td>
        <td>ton</td>
        <td><%= item['cog_height'] %>cm</td>
        <td class="acceptance_item"><%= item['result'] %></td>
        <td>
          <% if !item['remark'].blank? %>
            <% item['remark'].each do |remark| %>
              <p>- <%= remark%> </p>
            <%end%>
          <%end%>
        </td>
      </tr>

      
    <% end %>

    <tr class="result_container">
        <td colspan="2">TOTAL</td>
        <td><%= @result['total_length'] %></td>
        <td colspan="3">cm</td>
        <td><%= @result['total_weight'] %></td>
        <td colspan="2">ton</td>
        <td><%= @result['total_result'] %> </td>
        <td>
          <% if !@result['total_remark'].blank? %>
            <% @result['total_remark'].each do |total_remark| %>
              <p>- <%= total_remark%></p>
            <% end %>
          <%end%>
        </td>
      
    </tr>

  </table>

  <div class="conclusion">
    <h4>CONCLUSION OF YOUR INQUIRY</h4>
    <div class="group_conclusion d-flex justify-content-center">
        <p id="final_conclusion"><%= @result['final_conclusion'] %></p>
    </div>
  </div>

  <div class="btn btn-primary float-end mt-4">
    <%= link_to "Back", containers_path(@containers) %>
  </div>
</div>